# Generated by Django 4.2.26 on 2025-12-02 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.trainer'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.appointment'),
        ),
    ]
