# Generated by Django 4.2.26 on 2025-12-02 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_dietplan_trainer_alter_membership_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.trainer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Rescheduled', 'Rescheduled'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='memberships.trainee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='memberships.trainer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='memberships.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='memberships.trainee'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_memberships', to='memberships.appointment'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='memberships.trainee'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='memberships.trainer'),
        ),
    ]
